
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
      - php: 5.3
        dist: precise
      - php: 5.4
        dist: precise
      - php: 5.5
        dist: precise
      - php: 5.6
      - php: 7.0
  fast_finish: true

install:
  - composer install

script:
  - find -name '*.php' -not -path './vendor/*' -name '*.php' | xargs -n1 php -l
